plugins {
    id 'org.springframework.boot' version '3.4.4'
    id 'io.freefair.lombok' version '8.14'
    id 'org.sonarqube' version '7.3.1.8318'
}

gradle.startParameter.parallelProjectExecutionEnabled = true

sonar {
    properties {
        property "sonar.host.url", "https://sonarcloud.io"
    }
}

subprojects {
    group = 'net.trackme'
    version = '0.0.3-SNAPSHOT'

    repositories {
        mavenCentral()
        maven {
            url = uri('https://maven.pkg.github.com/Students-buisness-incubator-of-TUSUR/track-me-platform')
            credentials {
                username = project.findProperty('gpr.user') ?: System.getenv('GITHUB_ACTOR') ?: ''
                password = project.findProperty('gpr.key') ?: System.getenv('GITHUB_TOKEN') ?: ''
            }
        }
    }
}