plugins {
    id 'java'
    id 'war'
    id 'jacoco'
    id 'org.sonarqube' version '4.0.0.2929'
}

subprojects {
    apply plugin: 'war'
    apply plugin: 'java'
    apply plugin: 'jacoco'
    apply plugin: 'org.sonarqube'

    group = 'net.akarmanov.projectplace'
    version = '0.0.2-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    test {
        useJUnitPlatform()
        finalizedBy jacocoTestReport
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.required = true
            html.required = true
        }
    }

    sonar {
        properties {
            property "sonar.language", "java"
            property "sonar.sourceEncoding", "UTF-8"
        }
    }
}