rootProject.name = 'trackme'

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

include 'platform'

include ':backend'
project(':backend').projectDir = file('apps/backend')

include ':trackme-gateway'
project(':trackme-gateway').projectDir = file('apps/trackme-gateway')

include ':trackme-sso'
project(':trackme-sso').projectDir = file('services/trackme-sso')

include ':commons'
findProject(':commons').projectDir = file('libs/commons')

include ':meeting-service'
findProject(':meeting-service').projectDir = file('services/meeting-service')

include ':telegram-service'
project(':telegram-service').projectDir = file('services/telegram-service')
