plugins {
    id 'java-platform'
}

javaPlatform {
    allowDependencies()
}

group = 'net.trackme.platform'

dependencies {
    api platform('org.springframework.boot:spring-boot-dependencies:3.5.0')
    api platform('org.springframework.cloud:spring-cloud-dependencies:2024.0.1')
    api platform('org.junit:junit-bom:5.11.0')
    api platform('org.testcontainers:testcontainers-bom:1.19.0')

    constraints {
        api 'org.projectlombok:lombok:1.18.34'
        api 'org.springframework:spring-context:6.1.6'
        api 'org.springframework:spring-core:6.1.6'
        api 'jakarta.transaction:jakarta.transaction-api:2.0.1'
        api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'
        api 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.8.6'
        api 'org.springdoc:springdoc-openapi-starter-common:2.8.6'
        api 'org.springframework.security:spring-security-acl:6.4.4'
        api 'org.springframework.security:spring-security-core:6.4.4'
        api 'org.springframework.security:spring-security-oauth2-client:6.4.4'
        api 'org.springframework.security:spring-security-oauth2-jose:6.4.4'
        api 'org.springframework.security:spring-security-oauth2-resource-server:6.4.4'
        api 'org.springframework.security:spring-security-config:6.4.4'
        api 'org.springframework.security:spring-security-web:6.4.4'
        api 'org.springframework.security:spring-security-test:6.4.4'
        api 'org.mapstruct:mapstruct:1.6.2'
        api 'org.mapstruct:mapstruct-processor:1.6.2'
        api 'org.liquibase:liquibase-core:4.24.0'
        api 'io.github.wimdeblauwe:error-handling-spring-boot-starter:4.4.0'
        api 'org.telegram:telegrambots-spring-boot-starter:6.9.7.1'
        api 'org.apache.poi:poi-ooxml:5.3.0'
    }
}