plugins {
    id 'war'
    id 'java'
    id 'org.springframework.boot'
    id 'jacoco'
    id 'io.spring.dependency-management'
    id 'com.github.node-gradle.node'
}

version = '1.0.0'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.liquibase:liquibase-core'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.session:spring-session-jdbc'
    implementation 'org.springframework.session:spring-session-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    compileOnly 'org.projectlombok:lombok'
    implementation 'org.mapstruct:mapstruct:1.6.2'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'
    testImplementation 'org.springframework.security:spring-security-test'


    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
    runtimeOnly 'org.postgresql:postgresql'

    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.2'

    implementation project(':commons')
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDirs = ['src/main/resources', 'database', 'frontend']
        }
    }
}

springBoot {
    buildInfo()
}


node {
    version = '23.10.0'
    npmVersion = '10.9.2'
    download = !project.hasProperty('prod')
    nodeProjectDir = file("${projectDir}/frontend")
}

tasks.register('installReact', NpmTask) {
    args = ['install']
    workingDir = file("${projectDir}/frontend")
}

tasks.register('buildReact', NpmTask) {
    args = ['run', 'build']
    workingDir = file("${projectDir}/frontend")
    dependsOn installReact
    if (project.hasProperty('prod')) {
        environment = [
                'PUBLIC_URL'         : '/sso',
                'REACT_APP_BASE_PATH': '/sso'
        ]
    }
}

// Копируем ассеты
tasks.register('copyReactStatic', Copy) {
    dependsOn 'buildReact'
    from("${projectDir}/frontend/build/static")
    into("src/main/resources/static")
}

// Копируем index.html в шаблоны Thymeleaf
tasks.register('copyReactIndex', Copy) {
    dependsOn 'buildReact'
    from("${projectDir}/frontend/build/index.html")
    into("src/main/resources/templates")
}

processResources.dependsOn('copyReactStatic', 'copyReactIndex')