name: Build, Push, and Deploy

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write
  security-events: write

on:
  push:
    tags:
      - 'v*.*.*'
    branches: [ develop ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'

jobs:
  login-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  trackme-backend-build-push:
    needs: login-to-ghcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: apps/backend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
            ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
            ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  trackme-client-build-push:
    needs: login-to-ghcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push trackme-client Image
        uses: docker/build-push-action@v5
        with:
          context: apps/trackme-gateway
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/gateway:latest
            ghcr.io/${{ github.repository }}/gateway:${{ github.sha }}
            ghcr.io/${{ github.repository }}/gateway:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  trackme-sso-build-push:
    needs: login-to-ghcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push trackme-sso Image
        uses: docker/build-push-action@v5
        with:
          context: services/trackme-sso
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/sso:latest
            ghcr.io/${{ github.repository }}/sso:${{ github.sha }}
            ghcr.io/${{ github.repository }}/sso:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  trackme-frontend-build-push:
    needs: login-to-ghcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push trackme-frontend Image
        uses: docker/build-push-action@v5
        with:
          context: apps/frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/frontend:latest
            ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
            ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  set-env-and-deploy:
    needs:
      - trackme-backend-build-push
      - trackme-client-build-push
      - trackme-sso-build-push
      - trackme-frontend-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables and Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e

            # Перейти в рабочую директорию проекта
            cd /home/${{ secrets.SSH_USERNAME }}/track-me

            # Создать .env файл с переменными окружения
            rm -f .env .env.local

            echo "REACT_APP_CLIENT_GATEWAY_URI=${{ secrets.API_V1_BASE_URL }}" >> .env
            echo "GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}" >> .env
            echo "GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }}" >> .env
            echo "FRONTEND_URI=${{ secrets.FRONTEND_URI }}" >> .env
            echo "BACKEND_URI=${{ secrets.API_V1_BASE_URL }}" >> .env
            echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
            echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> .env
            echo "MAIL_SUBJECT=${{ secrets.MAIL_SUBJECT }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_URL=${{ secrets.DB_URL }}" >> .env
            echo "TRACKME_CLIENT_ID=${{ secrets.TRACKME_CLIENT_ID }}" >> .env
            echo "TRACKME_CLIENT_SECRET=${{ secrets.TRACKME_CLIENT_SECRET }}" >> .env
            echo "SSO_URI=${{ secrets.API_V1_BASE_URL }}/sso" >> .env
            echo "AFTER_LOGOUT_URI=${{ secrets.FRONTEND_URI }}" >> .env
            echo "GATEWAY_URI=${{ secrets.API_V1_BASE_URL }}/api" >> .env
            echo "NODE_ENV=development" >> .env
            echo "REACT_APP_ENV=dev" >> .env

            # Скачать новые версии image'ей
            docker compose -f docker/docker-compose.dev.yml pull

            # Остановить текущие контейнеры и поднять новые
            docker compose -f docker/docker-compose.dev.yml down
            docker compose -f docker/docker-compose.dev.yml up -d

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/vmv94/gateway/
            make restart
