name: Deploy to DEV
on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        description: 'Docker Image Tag to deploy'
        default: 'latest'
        type: string
  workflow_run:
    workflows:
      - 'Build and Push Docker Images'
    types:
      - completed
jobs:
  choose-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.image_tag }}
    steps:
      - name: Set tag depending on trigger
        id: set-image-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "image_tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=latest" >> $GITHUB_OUTPUT
          fi
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print SHA
        run: echo "Deploying commit ${{ github.event.workflow_run.head_sha }}"

      - name: Set Environment Variables
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SBI_SSH_HOST }}
          proxy_host: bastion.tusur.ru
          proxy_username: ${{ secrets.SBI_SSH_USERNAME }}
          proxy_key: ${{ secrets.SBI_SSH_PRIVATE_KEY }}
          username: ${{ secrets.SBI_SSH_USERNAME }}
          key: ${{ secrets.SBI_SSH_PRIVATE_KEY }}
          script: |
            set -e
            
            # Перейти в рабочую директорию проекта
            cd /home/${{ secrets.SBI_SSH_USERNAME }}/track-me-dev
            
            # Создать .env файл с переменными окружения
            rm -f .env
            
            echo "FRONTEND_URI=${{ secrets.DEV_FRONTEND_URI }}" >> .env
            echo "CORS_ORIGINS=${{ secrets.DEV_FRONTEND_URI }},http://localhost:3000" >> .env
            echo "AFTER_LOGOUT_URI=${{ secrets.DEV_FRONTEND_URI }}" >> .env
            echo "AFTER_LOGIN_URL=${{ secrets.DEV_FRONTEND_URI }}/after-login" >> .env
            echo "SSO_URI=${{ secrets.DEV_SSO_URI }}" >> .env
            
            echo "BACKEND_URI=${{ secrets.DEV_BACKEND_URI }}" >> .env
            echo "REACT_APP_BACKEND_URI=${{ secrets.DEV_BACKEND_URI }}" >> .env
            echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
            echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> .env
            echo "MAIL_SUBJECT=TrackMe" >> .env
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
            echo "TELEGRAM_BOT_USERNAME=${{ secrets.TELEGRAM_BOT_USERNAME }}" >> .env
            cat .env.dev.redis | tr -d '\r' >> .env
            echo "" >> .env
            cat .env.dev.database | tr -d '\r' >> .env
            echo "" >> .env
            cat .env.dev.sso | tr -d '\r' >> .env

  deploy:
    needs: [ set-env, choose-image-tag ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DEV
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SBI_SSH_HOST }}
          proxy_host: bastion.tusur.ru
          proxy_username: ${{ secrets.SBI_SSH_USERNAME }}
          proxy_key: ${{ secrets.SBI_SSH_PRIVATE_KEY }}
          username: ${{ secrets.SBI_SSH_USERNAME }}
          key: ${{ secrets.SBI_SSH_PRIVATE_KEY }}
          script: |
            set -e
            
            # Перейти в рабочую директорию проекта
            cd /home/${{ secrets.SBI_SSH_USERNAME }}/track-me-dev
            
            TAG='${{ needs.choose-image-tag.outputs.image_tag }}'
            
            # Скачать новые версии image'ей
            docker pull ghcr.io/${{ github.repository }}/backend:$TAG
            docker pull ghcr.io/${{ github.repository }}/gateway:$TAG
            docker pull ghcr.io/${{ github.repository }}/sso:$TAG
            docker pull ghcr.io/${{ github.repository }}/frontend:$TAG
            docker pull ghcr.io/${{ github.repository }}/meeting-service:$TAG
            docker pull ghcr.io/${{ github.repository }}/telegram-service:$TAG
            
            # Остановить текущие контейнеры и поднять новые
            docker compose -f docker-compose.dev.yml down
            docker compose -f docker-compose.dev.yml up -d
            
            # Удалить старые образы
            docker image prune -f
  

  healthcheck-services:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Healthcheck
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SBI_SSH_HOST }}
          proxy_username: ${{ secrets.SBI_SSH_USERNAME }}
          proxy_key: ${{ secrets.SBI_SSH_PRIVATE_KEY }}
          username: ${{ secrets.SBI_SSH_USERNAME }}
          key: ${{ secrets.SBI_SSH_PRIVATE_KEY }}
          proxy_host: bastion.tusur.ru
          script: |
            set -e
            
            # Проверить доступность сервисов
            until curl -sf http://localhost:8080/actuator/health; do
              echo "Waiting for backend..."
              sleep 5
            done
            
            until curl -sf http://localhost:9000/actuator/health; do
              echo "Waiting for sso..."
              sleep 5
            done
            
            until curl -sf http://localhost:3000/actuator/health; do
              echo "Waiting for frontend..."
              sleep 5
            done

  restart-nginx:
    needs: healthcheck-services
    runs-on: ubuntu-latest
    steps:
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SBI_SSH_HOST }}
          proxy_username: ${{ secrets.SBI_SSH_USERNAME }}
          proxy_key: ${{ secrets.SBI_SSH_PRIVATE_KEY }}
          username: ${{ secrets.SBI_SSH_USERNAME }}
          key: ${{ secrets.SBI_SSH_PRIVATE_KEY }}
          proxy_host: bastion.tusur.ru
          script: |
            sudo systemctl reload nginx