name: Deploy
on:
  schedule:
    - cron: '0 0 * * *'
  registry_package:
    types: [published, updated]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/track-me
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env
            docker pull ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/track-me-backend:latest
            docker stop track-me-backend || true
            docker rm track-me-backend || true
            docker compose up -d postgres backend

      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/track-me
            docker pull ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/track-me-frontend:latest
            docker stop track-me-frontend || true
            docker rm track-me-frontend || true
            docker compose up -d frontend