name: Deploy to Stage
on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        description: 'Docker Image Tag to deploy'
        default: 'latest'
        type: string
  workflow_run:
    workflows:
      - 'Build and Push Docker Images'
    types:
      - completed
jobs:
  choose-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.image_tag }}
    steps:
      - name: Set tag depending on trigger
        id: set-image-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "image_tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=latest" >> $GITHUB_OUTPUT
          fi
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print SHA
        run: echo "Deploying commit ${{ github.event.workflow_run.head_sha }}"

      - name: Set Environment Variables
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e
            
            # Перейти в рабочую директорию проекта
            cd /home/${{ secrets.SSH_USERNAME }}/track-me
            
            # Создать .env файл с переменными окружения
            rm -f .env
            
            echo "REACT_APP_CLIENT_GATEWAY_URI=${{ secrets.API_V1_BASE_URL }}/api" >> .env
            echo "FRONTEND_URI=https://xn--e1aaowdh.xn----gtbbcb4bjf2ak.xn--p1ai" >> .env
            echo "BACKEND_URI=${{ secrets.API_V1_BASE_URL }}" >> .env
            echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
            echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> .env
            echo "MAIL_SUBJECT=${{ secrets.MAIL_SUBJECT }}" >> .env
            echo "SSO_URI=${{ secrets.API_V1_BASE_URL }}/sso" >> .env
            echo "AFTER_LOGOUT_URI=https://xn--e1aaowdh.xn----gtbbcb4bjf2ak.xn--p1ai" >> .env
            echo "AFTER_LOGIN_URL=https://xn--e1aaowdh.xn----gtbbcb4bjf2ak.xn--p1ai/after-login" >> .env
            echo "GATEWAY_URI=${{ secrets.API_V1_BASE_URL }}/api" >> .env
            cat .env.dev.redis | tr -d '\r' >> .env
            echo "" >> .env
            cat .env.dev.database | tr -d '\r' >> .env
            echo "" >> .env
            cat .env.dev.sso | tr -d '\r' >> .env

  deploy:
    needs: [ set-env, choose-image-tag ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Stage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e
            
            # Перейти в рабочую директорию проекта
            cd /home/${{ secrets.SSH_USERNAME }}/track-me
            
            TAG='${{ needs.choose-image-tag.outputs.image_tag }}'
            
            # Скачать новые версии image'ей
            docker pull ghcr.io/${{ github.repository }}/backend:$TAG
            docker pull ghcr.io/${{ github.repository }}/gateway:$TAG
            docker pull ghcr.io/${{ github.repository }}/sso:$TAG
            docker pull ghcr.io/${{ github.repository }}/frontend:$TAG
            
            # Остановить текущие контейнеры и поднять новые
            docker compose -f docker-compose.dev.yml down
            docker compose -f docker-compose.dev.yml up -d
            
            # Удалить старые образы
            docker image prune -f
  

  healthcheck-services:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Healthcheck
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e
            
            # Проверить доступность сервисов
            until curl -sf http://localhost:8080/actuator/health; do
              echo "Waiting for backend..."
              sleep 5
            done
            
            until curl -sf http://localhost:9000/actuator/health; do
              echo "Waiting for sso..."
              sleep 5
            done
            
            until curl -sf http://localhost:3001/actuator/health; do
              echo "Waiting for frontend..."
              sleep 5
            done

  restart-nginx:
    needs: healthcheck-services
    runs-on: ubuntu-latest
    steps:
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/vmv94/gateway/
            make restart