name: Deploy on SBI

permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-on-sbi:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SBI_SSH_HOST }}
          username: ${{ secrets.SBI_SSH_USERNAME }}
          key: ${{ secrets.SBI_SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SBI_SSH_USERNAME }}/track-me
            rm -rf .env
            rm -rf .env.local
            echo "REACT_APP_CLIENT_GATEWAY_URI=${{ secrets.API_V1_BASE_URL }}" > .env.local
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "FRONTEND_URI=${{ secrets.FRONTEND_URI }}" >> .env
            echo "BACKEND_URI=${{ secrets.API_V1_BASE_URL }}" >> .env
            echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
            echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> .env
            docker compose -f docker-compose.sbi.yml down
            docker compose -f docker-compose.sbi.yml pull
            docker compose -f docker-compose.sbi.yml up -d
