name: Restrict Changes

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write
  security-events: write

on:
  pull_request:
    paths-ignore:
      - 'apps/frontend/**'

jobs:
  restrict-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        id: changes
        run: |
          echo "Автор pull request: $GITHUB_ACTOR"
          # Если автор не admin, прерываем сборку с ошибкой
          if [ "$GITHUB_ACTOR" != "akarmanov2022" ]; then
            echo "Ошибка: Пользователь $GITHUB_ACTOR не имеет прав вносить изменения в этот репозиторий, кроме папки apps/frontend"
            exit 1
          fi