name: Restrict Changes

on:
  pull_request:
    paths:
      - '**'
    branches:
      - develop

jobs:
  restrict-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract restricted developers from CODEOWNERS
        run: |
          restricted_developers=$(grep 'apps/frontend/*' .github/CODEOWNERS | awk '{for (i=2; i<=NF; i++) print $i}' | base64 | tr -d '\n')
          echo "RESTRICTED_DEVELOPERS=$restricted_developers" >> $GITHUB_ENV

      - name: Check for restricted changes outside of apps/frontend/
        run: |
          restricted_developers=$(echo "${RESTRICTED_DEVELOPERS}" | base64 --decode)
          IFS=' ' read -r -a developers_array <<< "$restricted_developers"
          if [[ " ${developers_array[@]} " =~ " ${GITHUB_ACTOR} " ]]; then
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -v '^apps/frontend/'; then
              echo "Changes outside of apps/frontend/ are not allowed for frontend developers."
              exit 1
            fi
          fi